apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.release_name }}
spec:
  selector:
    app: {{ .Values.release_name }}
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    name: http
